-- =====================================================================
--  Public RPCs: the two functions an anonymous visitor can call
-- =====================================================================
--
--  WHY THIS EXISTS
--
--  `submit_lead` and `subscribe_newsletter` are the only write paths open
--  to `anon`. They are also the two functions nobody exercises during
--  development, because filling in the contact form by hand is tedious and
--  the result — a row in a table you were not looking at — is invisible.
--
--  Migration 0062 added rate limiting to both and did not grant EXECUTE on
--  the limiter. `submit_lead` was SECURITY INVOKER, so every anonymous
--  submission failed with `42501: permission denied for function
--  consume_rate_limit`. The contact form was dead for as long as that
--  migration was live, and the only symptom was an empty `leads` table —
--  which looks exactly like a quiet week. 0064 fixed it. This file is what
--  would have caught it on day one.
--
--  Runs as `anon`, through the same function PostgREST calls, inside one
--  transaction that ends in ROLLBACK. Nothing is left behind, so it is safe
--  against production.
--
--      psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f tests/db/public-rpc.test.sql
-- =====================================================================

begin;
set local plpgsql.check_asserts = on;

-- ------------------------------------------------------------------
--  1. The happy path, and the limit, and the shape of the limit
-- ------------------------------------------------------------------

do $$
declare i int; ok boolean; ref text; n int;
begin
  execute 'set local role anon';
  execute 'set local request.jwt.claims = ''{"role":"anon"}''';

  -- Five inside the window succeed. Asserting on the returned reference and
  -- not merely on "no exception": the reference is generated by a trigger,
  -- so a non-null one is proof the row committed.
  for i in 1..5 loop
    ref := public.submit_lead(
      'Rate Limit Probe', 'ratelimit-probe@rls.test',
      'Automated probe verifying the fixed-window limiter accepts the first five.',
      null, null, null, null, null, 'rls-test');
    assert ref is not null and length(ref) > 3,
      format('RPC: enquiry %s of 5 returned no reference — the public contact form is broken', i);
  end loop;

  -- The sixth is refused in the database. Not in the browser, where it can
  -- be skipped by talking to PostgREST directly.
  ok := false;
  begin
    perform public.submit_lead(
      'Rate Limit Probe', 'ratelimit-probe@rls.test',
      'Automated probe verifying the sixth enquiry inside the window is refused.',
      null, null, null, null, null, 'rls-test');
  exception when others then
    ok := (sqlerrm ilike '%too many enquiries%');
  end;
  assert ok, 'RATE LIMIT: a sixth enquiry inside the 15-minute window was accepted';

  -- Keyed per address. A global counter would let one spammer close the
  -- contact form for everybody, which is a worse outage than the spam.
  ref := public.submit_lead(
    'Someone Else', 'other-probe@rls.test',
    'Automated probe verifying the limiter is keyed per address, not globally.',
    null, null, null, null, null, 'rls-test');
  assert ref is not null, 'RATE LIMIT: the limiter is global rather than per-address';

  -- Writing does not grant reading.
  select count(*) into n from public.leads;
  assert n = 0, format('RPC: anon can read %s lead(s) after submitting one', n);

  -- The general limiter is not reachable from outside. Its arguments include
  -- the limit and the window, so a caller who can reach it can set its own.
  ok := false;
  begin
    perform private.consume_rate_limit('anything', 'victim@example.com', 1, interval '1 hour');
  exception when insufficient_privilege then ok := true;
  end;
  assert ok, 'RATE LIMIT: anon can call the general limiter directly and choose its own limit';

  -- The narrow delegate (0065) IS reachable — that is its job — but it accepts
  -- only the buckets it knows. An unknown bucket must be refused, not created:
  -- silently creating one turns `rate_limits` into free storage.
  ok := false;
  begin
    perform private.consume_public_rate_limit('invented_bucket', 'victim@example.com');
  exception when others then ok := (sqlerrm ilike '%unknown rate limit bucket%');
  end;
  assert ok, 'RATE LIMIT: an invented bucket name was accepted by the public delegate';

  perform public.subscribe_newsletter('newsletter-probe@rls.test', 'rls-test');
end $$;
reset role;

-- ------------------------------------------------------------------
--  2. The bug CLASS, not just the bug
--
--  A SECURITY INVOKER function in `public` runs as the caller, so every
--  `private.*` helper it calls must be executable by that caller too.
--  Migration 0042 removed the default grants on `private`, which makes this
--  a standing trap: add a helper call to an existing public function and it
--  fails for anon only, in production only.
--
--  This asserts the trap is empty rather than asserting one instance of it.
-- ------------------------------------------------------------------

do $$
declare bad text;
begin
  with pub as (
    select p.oid, p.proname, pg_get_functiondef(p.oid) as def,
           has_function_privilege('anon', p.oid, 'execute')          as anon_can_call,
           has_function_privilege('authenticated', p.oid, 'execute') as auth_can_call
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prokind = 'f' and p.prosecdef = false
  ),
  calls as (
    select pub.proname as public_fn, pub.anon_can_call, pub.auth_can_call, m[1] as helper
      from pub, regexp_matches(pub.def, 'private\.([a-z0-9_]+)\s*\(', 'g') m
  )
  select string_agg(distinct format('%s() calls private.%s()', public_fn, helper), '; ')
    into bad
    from calls c
   where (c.anon_can_call
          and not has_function_privilege('anon', ('private.' || c.helper)::regproc, 'execute'))
      or (c.auth_can_call
          and not has_function_privilege('authenticated', ('private.' || c.helper)::regproc, 'execute'));

  assert bad is null,
    'GRANTS: SECURITY INVOKER function(s) in public call a private helper the caller may not execute — '
    || 'these fail with 42501 for real users and succeed for you: ' || coalesce(bad, '');
end $$;

select 'ALL PUBLIC RPC ASSERTIONS PASSED' as result;

rollback;
