import { expect, test } from "@playwright/test";

import { requireBackend } from "./backend";

/**
 * The enquiry path, end to end: form → Server Action → `submit_lead` → the
 * `leads` row → the trigger-generated reference → back into the DOM.
 *
 * This is the only workflow an anonymous visitor can drive all the way into the
 * database, which makes it the one place a browser test can prove the whole
 * chain without credentials. It matters here specifically: this form used to
 * resolve a 1.4-second timer and show a success screen. Nothing was stored.
 * Every enquiry sent through it was discarded, and the page looked perfect.
 *
 * The reference is asserted because it is the part that cannot be faked by the
 * client — it is generated by a database trigger and returned. A success
 * message proves nothing; a reference proves a row exists.
 *
 * WRITES. Each run inserts one lead. The address is unique per run, which also
 * keeps the 5-per-15-minutes rate limit (keyed on lower(email)) from tripping
 * across runs. Clean up with:
 *
 *     delete from public.email_outbox
 *      where payload->>'email' like 'e2e+%@nexus.test';
 *     delete from public.leads where email like 'e2e+%@nexus.test';
 */

// Serial: these write, and a rate limit is shared state.
test.describe.configure({ mode: "serial" });

const brief =
  "This enquiry was submitted by the automated end-to-end suite to verify that " +
  "the contact form reaches the database. It is safe to delete.";

/**
 * The footer carries a newsletter signup whose input is also labelled with an
 * email address, so a page-wide getByLabel("Email address") is ambiguous.
 * Everything below is scoped to the enquiry form itself.
 */
const enquiryForm = (page: import("@playwright/test").Page) =>
  page.locator("form").filter({ has: page.getByLabel("Project brief") });

test.describe("enquiry", () => {
  test("rejects an incomplete brief without contacting the server", async ({ page }) => {
    // Runs offline too: this is client-side validation, and it must fire before
    // a wasted round trip.
    await page.goto("/contact");

    await enquiryForm(page).getByLabel("Full name").fill("E2E Bot");
    await enquiryForm(page).getByLabel("Email address").fill("e2e@nexus.test");
    await enquiryForm(page).getByLabel("Project brief").fill("too short");
    await enquiryForm(page).getByRole("button", { name: /initialize connection/i }).click();

    await expect(page.getByText("A sentence or two about the project, please.")).toBeVisible();
    await expect(enquiryForm(page).getByText("Reference code")).toBeHidden();
  });

  test("requires a valid email address", async ({ page }) => {
    await page.goto("/contact");
    await enquiryForm(page).getByLabel("Full name").fill("E2E Bot");
    await enquiryForm(page).getByLabel("Email address").fill("not-an-email");
    await enquiryForm(page).getByLabel("Project brief").fill(brief);
    await enquiryForm(page).getByRole("button", { name: /initialize connection/i }).click();

    await expect(page.getByText("Enter a valid email address.")).toBeVisible();
  });

  test("a complete enquiry is stored and returns a reference", async ({ page }) => {
    await requireBackend();

    const email = `e2e+${Date.now()}@nexus.test`;

    await page.goto("/contact");
    await enquiryForm(page).getByLabel("Full name").fill("E2E Test Enquiry");
    await enquiryForm(page).getByLabel("Email address").fill(email);
    await enquiryForm(page).getByLabel("Project brief").fill(brief);
    await enquiryForm(page).getByRole("button", { name: /initialize connection/i }).click();

    await expect(enquiryForm(page).getByText("Reference code")).toBeVisible({ timeout: 20_000 });

    const reference = (await enquiryForm(page).locator("code[data-tabular]").innerText()).trim();
    // Generated server-side by the trigger; the browser has no way to produce
    // one, so its presence is proof the insert committed.
    expect(reference.length, "reference code came back empty").toBeGreaterThan(3);
    expect(reference).not.toMatch(/undefined|null|NaN/);
  });
});
