"use server";

import { revalidatePath } from "next/cache";
import { unstable_noStore as noStore } from "next/cache";

import { createClient } from "./server";
import type { Database } from "./types";

/**
 * Inbound leads.
 *
 * The contact form used to end at "TODO: POST to a real endpoint. Nothing
 * leaves the browser today." It validated, showed a success state, and dropped
 * the enquiry. Everything here exists so that cannot happen again.
 *
 * Submission is deliberately the only thing an anonymous visitor can do. The
 * insert policy pins status, assignee and organisation, so a crafted request
 * cannot plant a qualified, already-assigned lead into the pipeline — proven by
 * role-switched tests rather than assumed.
 */

export type LeadRow = Database["public"]["Tables"]["leads"]["Row"];
export type LeadStatus = Database["public"]["Enums"]["lead_status"];

export type Lead = LeadRow & {
  assignee: { id: string; full_name: string; email: string; avatar_url: string | null } | null;
  service: { title: string; slug: string } | null;
};

type Result<T = void> = T extends void
  ? { ok: true } | { error: string }
  : { ok: true; data: T } | { error: string };

/* ------------------------------------------------------------- public --- */

/**
 * Records an enquiry and returns its reference.
 *
 * The reference is handed straight back so the success screen can show it. It
 * is generated by a database trigger, so the number a visitor is told is the
 * number actually stored — not one this function invented and hoped matched.
 */
export async function submitLead(form: FormData): Promise<Result<{ reference: string }>> {
  const supabase = await createClient();

  const fullName = String(form.get("fullName") ?? "").trim();
  const email = String(form.get("email") ?? "").trim();
  const brief = String(form.get("brief") ?? "").trim();

  if (fullName.length < 2) return { error: "Please give your name." };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return { error: "Enter a valid email address." };
  if (brief.length < 10) return { error: "Tell us a little about the project." };

  const serviceId = String(form.get("servicePageId") ?? "").trim();

  // Goes through submit_lead rather than a direct insert. The insert policy
  // let anon write, but `insert ... returning` needs a SELECT policy too, and
  // anon deliberately has none — so every submission failed at the return step
  // while a friendly catch-all message hid the reason. The RPC returns only
  // the reference and grants no read access.
  const { data, error } = await supabase.rpc("submit_lead", {
    p_full_name: fullName,
    p_email: email,
    p_brief: brief,
    p_company: String(form.get("company") ?? "").trim() || undefined,
    p_phone: String(form.get("phone") ?? "").trim() || undefined,
    p_project_title: String(form.get("projectTitle") ?? "").trim() || undefined,
    p_service_page: serviceId || undefined,
    p_service_intent: String(form.get("serviceIntent") ?? "").trim() || undefined,
    p_source: String(form.get("source") ?? "web-form").trim() || "web-form",
  });

  if (error || !data) {
    // Surfaced in the server log so a failure is diagnosable, while the
    // visitor gets a sentence rather than a Postgres error.
    console.error("submitLead failed", error);
    return { error: "We could not record that just now. Please try again." };
  }

  revalidatePath("/admin/leads");
  return { ok: true, data: { reference: data as string } };
}

/* -------------------------------------------------------------- admin --- */

export async function listLeads(): Promise<Lead[]> {
  noStore();
  const supabase = await createClient();

  const { data } = await supabase
    .from("leads")
    .select(
      "*, assignee:profiles!leads_assignee_id_fkey ( id, full_name, email, avatar_url )," +
        " service:pages!leads_service_page_id_fkey ( title, slug )"
    )
    .order("created_at", { ascending: false });

  return (data ?? []) as unknown as Lead[];
}

export type LeadPipeline = {
  total: number;
  open: number;
  won: number;
  /** Null until something has been decided — see the view for why. */
  conversionPct: number | null;
  openValue: number;
  wonValue: number;
  unsized: number;
};

export async function getLeadPipeline(): Promise<LeadPipeline> {
  noStore();
  const supabase = await createClient();
  const { data } = await supabase.from("lead_pipeline").select("*").maybeSingle();

  return {
    total: Number(data?.total ?? 0),
    open: Number(data?.open_count ?? 0),
    won: Number(data?.won_count ?? 0),
    conversionPct: data?.conversion_pct === null || data?.conversion_pct === undefined
      ? null
      : Number(data.conversion_pct),
    openValue: Number(data?.open_value ?? 0),
    wonValue: Number(data?.won_value ?? 0),
    unsized: Number(data?.unsized_count ?? 0),
  };
}

export async function setLeadStatus(id: string, status: LeadStatus): Promise<Result> {
  const supabase = await createClient();

  // closed_at is paired with the status by a CHECK constraint, so it moves
  // with it here rather than being left for a caller to remember.
  const decided = status === "won" || status === "lost";
  const { error } = await supabase
    .from("leads")
    .update({
      status,
      closed_at: decided ? new Date().toISOString() : null,
      contacted_at: status === "contacted" ? new Date().toISOString() : undefined,
    })
    .eq("id", id);

  if (error) return { error: error.message };
  revalidatePath("/admin/leads");
  return { ok: true };
}

export async function updateLead(id: string, form: FormData): Promise<Result> {
  const supabase = await createClient();

  const value = form.get("estimatedValue");
  const estimated = value === null || String(value).trim() === "" ? null : Number(value);
  if (estimated !== null && (!Number.isFinite(estimated) || estimated < 0)) {
    return { error: "Estimated value cannot be negative." };
  }

  const { error } = await supabase
    .from("leads")
    .update({
      // Empty stays null so the forecast excludes it, rather than 0 dragging
      // the total down as though the work were worthless.
      estimated_value: estimated,
      assignee_id: String(form.get("assigneeId") ?? "").trim() || null,
      service_intent: String(form.get("serviceIntent") ?? "").trim() || null,
      notes: String(form.get("notes") ?? "").trim() || null,
    })
    .eq("id", id);

  if (error) return { error: error.message };
  revalidatePath("/admin/leads");
  return { ok: true };
}

export async function deleteLead(id: string): Promise<Result> {
  const supabase = await createClient();
  const { error } = await supabase.from("leads").delete().eq("id", id);
  if (error) return { error: error.message };
  revalidatePath("/admin/leads");
  return { ok: true };
}
