"use server";

import { revalidatePath } from "next/cache";
import { unstable_noStore as noStore } from "next/cache";

import { createClient } from "./server";
import type { Database } from "./types";

/**
 * Inbound leads.
 *
 * The contact form used to end at "TODO: POST to a real endpoint. Nothing
 * leaves the browser today." It validated, showed a success state, and dropped
 * the enquiry. Everything here exists so that cannot happen again.
 *
 * Submission is deliberately the only thing an anonymous visitor can do. The
 * insert policy pins status, assignee and organisation, so a crafted request
 * cannot plant a qualified, already-assigned lead into the pipeline — proven by
 * role-switched tests rather than assumed.
 */

export type LeadRow = Database["public"]["Tables"]["leads"]["Row"];
export type LeadStatus = Database["public"]["Enums"]["lead_status"];

export type Lead = LeadRow & {
  assignee: { id: string; full_name: string; email: string; avatar_url: string | null } | null;
  service: { title: string; slug: string } | null;
};

type Result<T = void> = T extends void
  ? { ok: true } | { error: string }
  : { ok: true; data: T } | { error: string };

/* ------------------------------------------------------------- public --- */

/**
 * Records an enquiry and returns its reference.
 *
 * The reference is handed straight back so the success screen can show it. It
 * is generated by a database trigger, so the number a visitor is told is the
 * number actually stored — not one this function invented and hoped matched.
 */
export async function submitLead(form: FormData): Promise<Result<{ reference: string }>> {
  const supabase = await createClient();

  const fullName = String(form.get("fullName") ?? "").trim();
  const email = String(form.get("email") ?? "").trim();
  const brief = String(form.get("brief") ?? "").trim();

  if (fullName.length < 2) return { error: "Please give your name." };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return { error: "Enter a valid email address." };
  if (brief.length < 10) return { error: "Tell us a little about the project." };

  const serviceId = String(form.get("servicePageId") ?? "").trim();

  // Goes through submit_lead rather than a direct insert. The insert policy
  // let anon write, but `insert ... returning` needs a SELECT policy too, and
  // anon deliberately has none — so every submission failed at the return step
  // while a friendly catch-all message hid the reason. The RPC returns only
  // the reference and grants no read access.
  const { data, error } = await supabase.rpc("submit_lead", {
    p_full_name: fullName,
    p_email: email,
    p_brief: brief,
    p_company: String(form.get("company") ?? "").trim() || undefined,
    p_phone: String(form.get("phone") ?? "").trim() || undefined,
    p_project_title: String(form.get("projectTitle") ?? "").trim() || undefined,
    p_service_page: serviceId || undefined,
    p_service_intent: String(form.get("serviceIntent") ?? "").trim() || undefined,
    p_source: String(form.get("source") ?? "web-form").trim() || "web-form",
  });

  if (error || !data) {
    // Surfaced in the server log so a failure is diagnosable, while the
    // visitor gets a sentence rather than a Postgres error.
    console.error("submitLead failed", error);
    return { error: "We could not record that just now. Please try again." };
  }

  revalidatePath("/admin/leads");
  return { ok: true, data: { reference: data as string } };
}

/* -------------------------------------------------------------- admin --- */

export async function listLeads(): Promise<Lead[]> {
  noStore();
  const supabase = await createClient();

  const { data } = await supabase
    .from("leads")
    .select(
      "*, assignee:profiles!leads_assignee_id_fkey ( id, full_name, email, avatar_url )," +
        " service:pages!leads_service_page_id_fkey ( title, slug )"
    )
    .order("created_at", { ascending: false });

  return (data ?? []) as unknown as Lead[];
}

export type LeadPipeline = {
  total: number;
  open: number;
  won: number;
  /** Null until something has been decided — see the view for why. */
  conversionPct: number | null;
  openValue: number;
  wonValue: number;
  unsized: number;
};

export async function getLeadPipeline(): Promise<LeadPipeline> {
  noStore();
  const supabase = await createClient();
  const { data } = await supabase.from("lead_pipeline").select("*").maybeSingle();

  return {
    total: Number(data?.total ?? 0),
    open: Number(data?.open_count ?? 0),
    won: Number(data?.won_count ?? 0),
    conversionPct: data?.conversion_pct === null || data?.conversion_pct === undefined
      ? null
      : Number(data.conversion_pct),
    openValue: Number(data?.open_value ?? 0),
    wonValue: Number(data?.won_value ?? 0),
    unsized: Number(data?.unsized_count ?? 0),
  };
}

export async function setLeadStatus(id: string, status: LeadStatus): Promise<Result> {
  const supabase = await createClient();

  // closed_at is paired with the status by a CHECK constraint, so it moves
  // with it here rather than being left for a caller to remember.
  const decided = status === "won" || status === "lost";
  const { error } = await supabase
    .from("leads")
    .update({
      status,
      closed_at: decided ? new Date().toISOString() : null,
      contacted_at: status === "contacted" ? new Date().toISOString() : undefined,
    })
    .eq("id", id);

  if (error) return { error: error.message };
  revalidatePath("/admin/leads");
  return { ok: true };
}

export async function updateLead(id: string, form: FormData): Promise<Result> {
  const supabase = await createClient();

  const value = form.get("estimatedValue");
  const estimated = value === null || String(value).trim() === "" ? null : Number(value);
  if (estimated !== null && (!Number.isFinite(estimated) || estimated < 0)) {
    return { error: "Estimated value cannot be negative." };
  }

  const { error } = await supabase
    .from("leads")
    .update({
      // Empty stays null so the forecast excludes it, rather than 0 dragging
      // the total down as though the work were worthless.
      estimated_value: estimated,
      assignee_id: String(form.get("assigneeId") ?? "").trim() || null,
      service_intent: String(form.get("serviceIntent") ?? "").trim() || null,
      notes: String(form.get("notes") ?? "").trim() || null,
    })
    .eq("id", id);

  if (error) return { error: error.message };
  revalidatePath("/admin/leads");
  return { ok: true };
}

export async function deleteLead(id: string): Promise<Result> {
  const supabase = await createClient();
  const { error } = await supabase.from("leads").delete().eq("id", id);
  if (error) return { error: error.message };
  revalidatePath("/admin/leads");
  return { ok: true };
}

/**
 * Turns a won lead into a customer account.
 *
 * This was the missing hand-off at the centre of the pipeline. Visitor →
 * service → form → lead → CRM all worked and then stopped: converting an
 * enquiry into an organisation meant an administrator retyping the company
 * name into the Clients screen, with nothing linking the two afterwards. The
 * `leads.organization_id` column existed for exactly this and nothing ever set
 * it, so a client account could never be traced back to the enquiry behind it.
 *
 * Idempotent: a lead already carrying an organisation returns that one instead
 * of creating a duplicate, because the obvious way for this to be called twice
 * is somebody clicking Convert again after a slow response.
 */
export async function convertLeadToClient(
  leadId: string,
  form: FormData
): Promise<Result<{ organizationId: string }>> {
  const supabase = await createClient();

  const { data: lead, error: readError } = await supabase
    .from("leads")
    .select("id, full_name, email, company, organization_id")
    .eq("id", leadId)
    .maybeSingle();

  if (readError) return { error: readError.message };
  if (!lead) return { error: "That lead no longer exists." };
  if (lead.organization_id) {
    return { ok: true, data: { organizationId: lead.organization_id } };
  }

  // The company on the enquiry is a starting point, not a decision — an admin
  // converting a lead usually wants to tidy the name first.
  const name =
    String(form.get("organizationName") ?? "").trim() ||
    lead.company?.trim() ||
    lead.full_name.trim();
  if (name.length < 2) return { error: "Give the client account a name." };

  const industry = String(form.get("industry") ?? "").trim() || null;
  let organizationId = String(form.get("organizationId") ?? "").trim();

  if (!organizationId) {
    const base =
      name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "") || "client";
    const { data: allocated } = await supabase.rpc("next_available_slug", {
      p_table: "organizations",
      p_base: base,
    });

    const { data: org, error: orgError } = await supabase
      .from("organizations")
      .insert({
        name,
        slug: allocated ?? base,
        industry,
        // A converted lead has not been onboarded yet; defaulting to "healthy"
        // would drop a brand-new account straight into the healthy bucket on
        // the client health report.
        health: "onboarding",
      })
      .select("id")
      .single();

    if (orgError || !org) {
      return { error: orgError?.message ?? "Could not create the client account." };
    }
    organizationId = org.id;
  }

  const { error: linkError } = await supabase
    .from("leads")
    .update({
      organization_id: organizationId,
      status: "won",
      closed_at: new Date().toISOString(),
    })
    .eq("id", leadId);

  if (linkError) return { error: linkError.message };

  revalidatePath("/admin/leads");
  revalidatePath("/admin/clients");
  revalidatePath("/admin/projects");
  return { ok: true, data: { organizationId } };
}
